apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-devops-sem7-expreg
  labels:
    project: devops-sem7
spec:
  selector:
    matchLabels:
      app: devops-sem7-expreg
  template:
    metadata:
      name: pod-template-devops-sem7-expreg
      labels:
        app: devops-sem7-expreg
        role: app-service
        env: production
        version: "1.0.0"
    spec:
      containers:
        - name: devops-sem7-expreg
          image: davintristan/devops_sem7_expreg:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: secret-devops-sem7-expreg-comm
            - configMapRef:
                name: configmap-devops-sem7-expreg
          resources:
            requests:
              cpu: "500m" # Required for HPA to calculate CPU utilization
