apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-pod-autoscaler-devops-sem7-expreg
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-devops-sem7-expreg
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70