services:
  backend:
    container_name: devops_sem7_server
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    environment:
      DOCKER: 1
      ACCESS_TOKEN_SECRET: secret_access
      REFRESH_TOKEN_SECRET: secret_refresh
      EXPRESSION_RECOGNITION_API_URL: http://devops_sem7_expreg:8000
      EXPRESSION_RECOGNITION_API_SECRET: secret_expression
      POSTGRES_USER: Parallel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: parallel
      POSTGRES_HOST: devops_sem7_postgresql
  expression_recognition:
    container_name: devops_sem7_expreg
    build:
      dockerfile: ./expression_recognition/Dockerfile
    ports:
      - 8001:8000
    environment:
      DOCKER: 1
      EXPRESSION_RECOGNITION_API_SECRET: secret_expression
      API_SERVER_URL: http://devops_sem7_server:8000
  postgres:
    container_name: devops_sem7_postgresql
    image: postgres:15.4-alpine
    ports:
      - 54320:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Parallel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: parallel

volumes:
  postgres:
