apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-devops-sem7-database
  labels:
    app: devops-sem7
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres
