apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-devops-sem7-database
  labels:
    project: devops-sem7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
