apiVersion: v1
kind: Service
metadata:
  name: service-devops-sem7-database
  labels:
    app: devops-sem7
    reachability: internal
spec:
  type: NodePort
  selector:
    matchLabels:
      entity: devops-sem7-database
  ports:
    - protocol: TCP
      port: 5432 # Port accessible within the cluster
      targetPort: 5432 # Maps to containerPort
