apiVersion: v1
kind: Service
metadata:
  name: service-devops-sem7-server
  labels:
    project: devops-sem7
    reachability: external
spec:
  type: NodePort
  selector:
    app: service-devops-sem7-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 # Expose this service in localhost
