apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-devops-sem7-server
data:
  DOCKER: 1
  EXPRESSION_RECOGNITION_API_URL: http://service-devops-sem7-expreg.svc.cluster.local:8000
  POSTGRES_HOST: service-devops-sem7-database.svc.cluster.local
