name: CI

on:
  push:
    branches:
      - release

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Deploy to DockerHub
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Atau versi Node.js yang Anda gunakan

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set up .env.local
        working-directory: ./frontend
        run: cp .env.local.example .env.local

      - name: Export files
        working-directory: ./frontend
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker compose -f docker-compose.yml build
      
      - name: Push image
        run: docker compose -f docker-compose.yml push
